{% set name = "freetype-py" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: f9b64ce3272a5c358dcee824800a32d70997fb872a0965a557adca20fce7a5d0

build:
  noarch: python
  number: 0
  # Note: --no-deps is currently required due to https://github.com/conda/conda-build/issues/3254
  # Once resolved, it should be removed.
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - freetype

test:
  imports:
    - freetype

about:
  home: https://github.com/rougier/freetype-py
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python binding for the freetype library
  description: |
    Freetype Python provides bindings for the FreeType library.
    Only the high-level API is bound.
  doc_url: https://freetype-py.readthedocs.io/
  dev_url: https://github.com/rougier/freetype-py

extra:
  recipe-maintainers:
    - hoechenberger
    - kastman
